* postgresql_secure_wal_transfer: fixed WAL regex + add debug info

diff --git a/postgresql_secure_wal_transfer b/postgresql_secure_wal_transfer
--- a/postgresql_secure_wal_transfer
+++ b/postgresql_secure_wal_transfer
@@ -50,9 +50,9 @@ then
 fi
 
 # Check wal_file
-if ! echo "$wal_file" | grep -qE "^[a-z0-9\.]+$"
+if ! echo "$wal_file" | grep -qE "^[A-Z0-9\.]+$"
 then
-    echo "$0: invalid WAL file name" >&2
+    echo "$0: invalid WAL file name $wal_file" >&2
     usage
     exit 2
 fi
